application: learn-to-code-1064 
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static/css
  static_dir: static/css

- url: /.*
  script: guestbook.app



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

